[package]
name = "vbsp-entities"
version = "0.1.0"
edition = "2024"

[features]
default = [
	"css",
]
css = []

[dependencies]
serde = "1.0.218"
vbsp = { git = "https://github.com/krakow10/vbsp", rev = "06ac1fdd29618db154a81fbc4ceb3cfe558d2671" }
