[package]
name = "vbsp-entities"
version = "0.1.0"
edition = "2024"

[features]
default = [
	"css",
	"tf2",
]
css = []
tf2 = []

[dependencies]
serde = "1.0.218"
vbsp = { version = "0.7.0-codegen5", registry = "strafesnet", default-features = false }
